version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: leapy_pg
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-leapy}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
#      - ./seed/schema.sql:/docker-entrypoint-initdb.d/00_schema.sql:ro
#      - ./seed/seed.sql:/docker-entrypoint-initdb.d/10_seed.sql:ro

  directus:
    image: directus/directus:10
    container_name: leapy_directus
    depends_on:
      - postgres
    ports:
      - "${PORT:-8055}:8055"
    environment:
      KEY: ${KEY:-supersecretkey}
      SECRET: ${SECRET:-supersecretsecret}
      PUBLIC_URL: ${PUBLIC_URL:-http://localhost:8055}
      DB_CLIENT: pg
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: ${POSTGRES_DB:-leapy}
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@example.com}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin}
      DIRECTUS_EXPERIMENTAL_GRAPHQL_INTROSPECTION: "true"
      EXTENSIONS_AUTO_RELOAD: "true"
    volumes:
      - ./extensions:/directus/extensions

volumes:
  pg_data:
